### ISSUE TITLE
Invalid subscription

### ISSUE THREAD

**Issue by jorisberg** [buddydev/buddycommerce#1]
Hi
When I activate the subscription i can see my subscriptions. However when I click on a subscription i get the error: Invalid subscription.

From the woocommerce-subscription integration i see that this message is generated in this functions:

```
public static function get_view_subscription_template( $subscription_id ) {
		$subscription = wcs_get_subscription( absint( $subscription_id ) );
		if ( ! $subscription || ! current_user_can( 'view_order', $subscription->get_id() ) ) {
			echo '<div class="woocommerce-error">' . esc_html__( 'Invalid Subscription.', 'woocommerce-subscriptions' ) . ' <a href="' . esc_url( wc_get_page_permalink( 'myaccount' ) ) . '" class="wc-forward">'. esc_html__( 'My Account', 'woocommerce-subscriptions' ) .'</a>' . '</div>';
			return;
		}
		wc_get_template( 'myaccount/view-subscription.php', compact( 'subscription' ), '', plugin_dir_path( WC_Subscriptions::$plugin_file ) . 'templates/' );
	}
```

**Comment by sbrajesh** [comment]
Hi,
I am sorry I did not see it earlier. 
Can you please confirm if you are still facing the same issue?

**Comment by jorisberg** [comment]
yes issue still persist, or did u update the code in the meantime?

**Comment by sbrajesh** [comment]
No, I did not update it. I tried on a local setup and could not reproduce it. That's why asked about it.

Can you please share a bit more on how to reproduce the issue. 
Is there any customization related to the subscription plugin on your site?
